### PR TITLE
2023 sem 1

### PR DESCRIPTION
**Pull request by Jake-Moss**
This addresses some comments in #11, however malformed data for `BIOC3000.json` and such still exist. I'll tackle them in a bit

### CODE REVIEW

**Comment by Jake-Moss** [comment]
Looks like its incorrectly parsing courses where there exists multiple tables, i.e. `PSYC3010.json`

https://course-profiles.uq.edu.au/student_section_loader/section_5/127014

Doesn't seem like a breaking issue and looks like the site has handled these fine in the past.

**Comment by gricey432** [comment]
Most years the "handling" is done by me manually correcting thousands of these. Too hard to automate all the inconsistencies

**Comment by Jake-Moss** [comment]
@gricey432 I've cleaned up the vast majority of stuff that's clearly not an assessment piece. There still remains some stuff that's not quite right but it would require manual checking of ecps and I can't procrastinate any longer

**Comment by gricey432** [comment]
Definitely better than what is currently live (nothing). Appreciate the contrib!

**Comment by gricey432** [comment]
Looks like it's all released successfully

**Pull request merged**
